/**
 * The word pool the game builds rare monster names from — every captured beast
 * shows one, and the Bestiary search reads it. "Darkmauler" is MONSTER_PREFIX
 * "Dark" plus MONSTER_SUFFIX "mauler"; a title like "the Relentless" may follow.
 *
 * A search fragment that can occur inside any of these names would match beasts
 * at random, so the generator refuses it.
 *
 * Extracted from Words.dat via poe-dat-viewer — see
 * scripts/update-monster-words.mjs. 167 prefixes,
 * 211 suffixes, 217 titles, which
 * together spell 35,237 possible names.
 */
export const MONSTER_NAME_PREFIXES: string[] = [
  "Acid",
  "Acrid",
  "Agony",
  "Alabaster",
  "Amber",
  "Ash",
  "Assault",
  "Auric",
  "Azure",
  "Bane",
  "Beach",
  "Bile",
  "Blight",
  "Blitz",
  "Blood",
  "Blue",
  "Bold",
  "Brass",
  "Brave",
  "Breeze",
  "Bright",
  "Brine",
  "Broken",
  "Brutal",
  "Cage",
  "Casket",
  "Cave",
  "Coffin",
  "Copper",
  "Crimson",
  "Cruel",
  "Crust",
  "Crypt",
  "Dark",
  "Death",
  "Dim",
  "Dire",
  "Dirt",
  "Doom",
  "Dread",
  "Dry",
  "Dusk",
  "Dust",
  "Earth",
  "Ebon",
  "Faith",
  "Fathom",
  "Fear",
  "Filth",
  "Flame",
  "Fog",
  "Foul",
  "Fury",
  "Gaunt",
  "Gilded",
  "Gilt",
  "Gloom",
  "Gold",
  "Golden",
  "Gore",
  "Granite",
  "Grave",
  "Gravel",
  "Gray",
  "Green",
  "Grey",
  "Grim",
  "Grime",
  "Gristle",
  "Gruff",
  "Gust",
  "Hairy",
  "Havoc",
  "Hollow",
  "Honour",
  "Horror",
  "Ichor",
  "Imperial",
  "Infernal",
  "Inferno",
  "Iron",
  "Just",
  "Justice",
  "Kelp",
  "Lava",
  "Light",
  "Luna",
  "Magma",
  "Marble",
  "Marrow",
  "Meat",
  "Might",
  "Mist",
  "Moon",
  "Moss",
  "Murder",
  "Night",
  "Noble",
  "Noxious",
  "Ocher",
  "Onyx",
  "Ooze",
  "Ore",
  "Pain",
  "Pebble",
  "Pit",
  "Poison",
  "Pummice",
  "Pure",
  "Pus",
  "Quartz",
  "Rage",
  "Razor",
  "Regal",
  "Relic",
  "Righteous",
  "Rock",
  "Rot",
  "Rubble",
  "Sand",
  "Scarlet",
  "Scum",
  "Sea",
  "Shadow",
  "Shaggy",
  "Shale",
  "Sharp",
  "Shiver",
  "Silver",
  "Sin",
  "Slag",
  "Slate",
  "Slender",
  "Slime",
  "Soil",
  "Sol",
  "Sorrow",
  "Star",
  "Steel",
  "Stench",
  "Stink",
  "Stoic",
  "Stone",
  "Storm",
  "Sun",
  "Swift",
  "Talc",
  "Tempest",
  "Terror",
  "Tidal",
  "Tide",
  "Tomb",
  "Tough",
  "Toxic",
  "Toxin",
  "Vaal",
  "Vault",
  "Venom",
  "Vile",
  "War",
  "Wave",
  "White",
  "Wind",
  "Woe",
  "Wrath",
  "Yellow",
  "Zephyr",
];

export const MONSTER_NAME_SUFFIXES: string[] = [
  "adder",
  "back",
  "band",
  "barb",
  "barbs",
  "beard",
  "beat",
  "bellow",
  "bite",
  "biter",
  "blade",
  "blood",
  "boil",
  "boiler",
  "bone",
  "bones",
  "bore",
  "brand",
  "break",
  "breaker",
  "bringer",
  "broken",
  "brow",
  "brute",
  "cackle",
  "call",
  "caller",
  "champion",
  "chew",
  "chewer",
  "choke",
  "churn",
  "clack",
  "clatter",
  "claw",
  "claws",
  "click",
  "crawl",
  "creak",
  "crest",
  "crush",
  "crusher",
  "dart",
  "darter",
  "drench",
  "drifter",
  "drool",
  "drown",
  "dweller",
  "eye",
  "eyes",
  "face",
  "fang",
  "fangs",
  "fate",
  "fist",
  "fists",
  "flay",
  "flayer",
  "flight",
  "flutter",
  "frag",
  "frenzy",
  "froth",
  "fur",
  "fury",
  "gasp",
  "gnash",
  "gnaw",
  "grin",
  "grind",
  "grinder",
  "grip",
  "growl",
  "guard",
  "guardian",
  "hackles",
  "hammer",
  "hand",
  "heart",
  "helm",
  "hilt",
  "hiss",
  "howl",
  "jaw",
  "jaws",
  "joint",
  "jowls",
  "kill",
  "killer",
  "knife",
  "knock",
  "lash",
  "lasher",
  "laugh",
  "limp",
  "lord",
  "lurch",
  "mark",
  "maul",
  "mauler",
  "maw",
  "mind",
  "moan",
  "moil",
  "muzzle",
  "needle",
  "needles",
  "pelt",
  "phantom",
  "pincers",
  "pinch",
  "prowl",
  "prowler",
  "quill",
  "rake",
  "raker",
  "rattle",
  "rattles",
  "razor",
  "render",
  "ribbon",
  "ribs",
  "ripper",
  "roar",
  "rope",
  "rot",
  "ruckus",
  "rumble",
  "scale",
  "scales",
  "scalp",
  "scar",
  "scrabbler",
  "scrape",
  "scream",
  "screech",
  "scuttle",
  "seethe",
  "sentinel",
  "sentry",
  "shamble",
  "shard",
  "shards",
  "shell",
  "shield",
  "shiver",
  "shriek",
  "shrieker",
  "shuffle",
  "skull",
  "slash",
  "slasher",
  "slice",
  "slicer",
  "slink",
  "slip",
  "slither",
  "sliver",
  "smash",
  "smasher",
  "smith",
  "snarl",
  "soak",
  "soul",
  "specter",
  "spine",
  "spirit",
  "splash",
  "splinter",
  "splinters",
  "spool",
  "spray",
  "spume",
  "stalker",
  "stench",
  "sting",
  "stink",
  "strangle",
  "stride",
  "strider",
  "sucker",
  "sunder",
  "surge",
  "talon",
  "talons",
  "teeth",
  "thirst",
  "tongue",
  "tooth",
  "tusk",
  "tusks",
  "twine",
  "tyrant",
  "viper",
  "visage",
  "voice",
  "wail",
  "walker",
  "ward",
  "watch",
  "watcher",
  "whip",
  "whipper",
  "whisper",
  "widow",
  "wight",
  "wing",
  "wither",
  "wraith",
  "zeal",
];

export const MONSTER_NAME_TITLES: string[] = [
  ", Child of God",
  ", Dominus' Favoured",
  ", Thrall of Dominus",
  "the Accursed",
  "the Adorned",
  "the Ancient",
  "the Annihilator",
  "the Baleful",
  "the Binder",
  "the Blasphemer",
  "the Blasphemous",
  "the Blessed",
  "the Blooddrinker",
  "the Bloodthirsty",
  "the Boiling",
  "the Bold",
  "the Bonebreaker",
  "the Bonechewer",
  "the Bonecruncher",
  "the Bottomless",
  "the Braineater",
  "the Brave",
  "the Breaker",
  "the Brittle",
  "the Brutal",
  "the Butcher",
  "the Callous",
  "the Champion",
  "the Child of God",
  "the Churning",
  "the Clanking",
  "the Clean",
  "the Cleansed",
  "the Cleanser",
  "the Clear",
  "the Corrupted",
  "the Corrupter",
  "the Cracked",
  "the Crazed",
  "the Cripple",
  "the Crippler",
  "the Cruel",
  "the Cunning",
  "the Cursed",
  "the Damned",
  "the Dauntless",
  "the Deadly",
  "the Decorated",
  "the Defiler",
  "the Demented",
  "the Depraved",
  "the Destroyer",
  "the Devoted",
  "the Devourer",
  "the Devout",
  "the Drenched",
  "the Dripping",
  "the Drooling",
  "the Drowned",
  "the Drowner",
  "the Dry",
  "the Ensnaring",
  "the Eternal",
  "the Ethereal",
  "the Ever-hungry",
  "the Ever-thirsty",
  "the Executioner",
  "the Faceshredder",
  "the Faithful",
  "the Faithless",
  "the Fallen",
  "the Fathomstalker",
  "the Fearless",
  "the Ferocious",
  "the Filthy",
  "the Fixthis",
  "the Foaming",
  "the Forsaken",
  "the Foul",
  "the Furious",
  "the Furry",
  "the Ghastly",
  "the Gilded",
  "the Glistening",
  "the Glorious",
  "the Grotesque",
  "the Groveling Servant",
  "the Guardian",
  "the Haggard",
  "the Harrying",
  "the Hateful",
  "the Heretic",
  "the Hideous",
  "the Hollow",
  "the Holy",
  "the Honest",
  "the Honourable",
  "the Honoured",
  "the Howler",
  "the Hulking",
  "the Hungry",
  "the Imperial",
  "the Imperious",
  "the Impervious",
  "the Incorporeal",
  "the Inquisitor",
  "the Insane",
  "the Ironclad",
  "the Irredeemable",
  "the Limb Tearer",
  "the Lumbering",
  "the Lurching",
  "the Mad",
  "the Magnificent",
  "the Malignant",
  "the Mangy",
  "the Menacing",
  "the Merciless",
  "the Mistwalker",
  "the Moiling",
  "the Monstrous",
  "the Nightwalker",
  "the Noxious",
  "the Oathbreaker",
  "the Oathkeeper",
  "the Panting",
  "the Parched",
  "the Patient",
  "the Penitent",
  "the Pious",
  "the Poisonous",
  "the Psychotic",
  "the Pure",
  "the Purifier",
  "the Quaking",
  "the Ravager",
  "the Ravenous",
  "the Reaver",
  "the Reborn",
  "the Redeemed",
  "the Relentless",
  "the Renowed",
  "the Repulsive",
  "the Resolute",
  "the Returned",
  "the Righteous",
  "the Rotted",
  "the Ruinous",
  "the Rumbling",
  "the Ruthless",
  "the Sadistic",
  "the Salty",
  "the Savage",
  "the Scarred",
  "the Scurrilous",
  "the Seething",
  "the Sentinel",
  "the Servant of God",
  "the Servile",
  "the Shaggy",
  "the Shuffler",
  "the Shuffling",
  "the Sickening",
  "the Silent",
  "the Sin Lord",
  "the Slayer",
  "the Slithering",
  "the Smasher",
  "the Smooth",
  "the Soaring",
  "the Sodden",
  "the Spinebreaker",
  "the Squalid",
  "the Stalker",
  "the Steadfast",
  "the Stinking",
  "the Subjugator",
  "the Supplicant",
  "the Supreme",
  "the Swift",
  "the Swirling",
  "the Sworn",
  "the Terrible",
  "the Terrifying",
  "the Throatslitter",
  "the Thundering",
  "the Titanic",
  "the Tormented",
  "the Tormenter",
  "the Toxic",
  "the Tunneler",
  "the Twining",
  "the Twisted",
  "the Tyrant",
  "the Unbreakable",
  "the Unclean",
  "the Undying",
  "the Unfeeling",
  "the Unflinching",
  "the Unmatched",
  "the Unsmiling",
  "the Unspeakable",
  "the Unwashed",
  "the Vengeant",
  "the Vengeful",
  "the Venomous",
  "the Voracious",
  "the Warden",
  "the Washed",
  "the Watching",
  "the Wicked",
  "the Widowmaker",
  "the Woebearer",
  "the Wretched",
  "the Yowler",
  "the Zealot",
  "the Zealous",
];
