/**
 * Every generic monster modifier a captured beast can carry: the internal
 * name, the name the Bestiary prints, and the effect text.
 *
 * This is the pool behind lines like "Soul Eater" or "Life Cannot Be Leeched"
 * on a beast that has nothing to do with the Bestiary league. The search reads
 * them exactly like the beast's own name, so a fragment found anywhere in here
 * would match beasts at random and is refused.
 *
 * Generated from the PoE Wiki monster prefix and suffix lists. 352
 * lines. Regenerate with scripts/update-monster-mods.mjs.
 */
export const MONSTER_MOD_TEXT: string[] = [
  "+100% chance to Suppress Spell Damage Prevent 50% of Suppressed Spell Damage",
  "+60% to Chaos Resistance 80% reduced Wither Duration on Self",
  "+75% to Cold Resistance 80% reduced Effect of Chill on you 80% increased Freeze Duration on you",
  "+75% to Fire Resistance 80% reduced Ignite Duration on you",
  "+75% to Lightning Resistance 80% reduced Effect of Shock on you",
  "1",
  "100% chance to gain a Frenzy Charge on Hit",
  "100% chance to Reflect Hexes",
  "100% increased Evasion Rating",
  "100% increased Global Accuracy Rating",
  "100% of Damage Leeched as Life 500% increased total Recovery per second from Life Leech",
  "12",
  "13",
  "15",
  "150% faster start of Energy Shield Recharge 40% of Maximum Life is added to Maximum Energy Shield",
  "18",
  "20% increased Damage with Hits per 10% missing Enemy Life",
  "24",
  "25% chance to Freeze",
  "300% increased Global Critical Strike Chance",
  "34",
  "39",
  "40% increased maximum Life",
  "40% increased Movement Speed 30% increased Attack and Cast Speed",
  "46",
  "50% additional Physical Damage Reduction",
  "50% Chance to Block Attack Damage",
  "50% increased Damage +30% to all Elemental Resistances +20% to Chaos Resistance 10% additional Physical Damage Reduction Spawns apparitions of Abberath which use his skills",
  "50% increased Damage +30% to all Elemental Resistances +20% to Chaos Resistance 10% additional Physical Damage Reduction Spawns apparitions of Arakaali which use her skills",
  "50% increased Damage +30% to all Elemental Resistances +20% to Chaos Resistance 10% additional Physical Damage Reduction Spawns apparitions of Lunaris which use her skills",
  "50% increased Damage +30% to all Elemental Resistances +20% to Chaos Resistance 10% additional Physical Damage Reduction Spawns apparitions of Shakari which use her skills",
  "50% increased Damage +30% to all Elemental Resistances +20% to Chaos Resistance 10% additional Physical Damage Reduction Spawns apparitions of Solaris which use her skills",
  "50% increased Damage +30% to all Elemental Resistances +20% to Chaos Resistance 10% additional Physical Damage Reduction Spawns apparitions of Tsoagoth which use his skills",
  "50% increased Damage +30% to all Elemental Resistances +20% to Chaos Resistance 10% additional Physical Damage Reduction Spawns apparitions of Tukohama which use his skills",
  "50% increased Damage +40% to all Elemental Resistances +25% to Chaos Resistance 15% additional Physical Damage Reduction Spawns apparitions of Innocence which use his skills",
  "50% increased Damage +40% to all Elemental Resistances +25% to Chaos Resistance 15% additional Physical Damage Reduction Spawns apparitions of Kitava which use his skills",
  "6",
  "68",
  "80% increased Area of Effect",
  "Abberath-touched",
  "Accurate",
  "Action Speed cannot be modified to below base value Movement Speed cannot be modified to below base value",
  "Adaptive Resistances",
  "All hits are Critical Strikes",
  "Always Crits",
  "Always Stuns Enemies on Hit",
  "Ambushes",
  "Applies Crushed on Hit",
  "Applies Random Mark",
  "Applies the Intervention buff to nearby allies for 5 seconds with a 6 second cooldown Intervention buff is removed on death Allies with Intervention cannot gain Intervention",
  "Applies Thorned Vines to Enemies, which slows them and causes them to take Chaos Damage over Time (3 second cooldown, 2 second global cooldown) Moving will break the Vines over time Travel Skills will break all Vines instantly",
  "Arakaali-touched",
  "Astral-touched",
  "Attacks cause Bleeding",
  "Baroness's",
  "Benevolent",
  "Berserking",
  "Bleeds",
  "Blind on Hit 100% increased Blind Effect",
  "Blinds",
  "Blocks Attacks",
  "Blurred",
  "Brine King-touched",
  "Burning Ground on Death",
  "Cannot be Slowed",
  "Cannot be Stunned",
  "Carapaced",
  "caster 0 default 1500",
  "caster 0 default 2500",
  "caster 0 default 5000",
  "caster 2000",
  "Casts Lightning Storms targeting Enemies",
  "Caustic Orb on Death",
  "Chaining",
  "Chance to Freeze",
  "Chaos and Wither Resistant",
  "Charge Removal",
  "Charged",
  "Chilled Ground on Death",
  "Cold Walker's",
  "Cold, Chill and Freeze Resistant",
  "Consecrated Ground",
  "Constantly Revives Minions",
  "Corrupting",
  "Creates areas of burning ground on death",
  "Creates areas of chilled ground on death",
  "Creates areas of shocked ground on death",
  "Creates Corpses nearby (10 second cooldown) Ignites nearby Corpses (green effect), detonating them after a short duration",
  "Creates Frost Walls and Flees",
  "Creates Orbs on death that chases the player, accelerating over time Caustic Orbs create Caustic Ground after exploding",
  "Creates Voodoo Doll",
  "Crit Resistant",
  "Crushing",
  "Crystalline",
  "Curses",
  "Cursing",
  "default 1000",
  "default 1500",
  "default 2000",
  "default 2500",
  "default 3000",
  "default 500",
  "default 5000",
  "default 800",
  "default 8000",
  "Elemental Equilibrium and Random Elemental Damage",
  "Empowering",
  "Empowers Allies",
  "Endurance Charge when Hit",
  "Enemies Cannot Leech Life From you",
  "Energy Shield Aura",
  "Energy Shield Explodes",
  "Enrages as Life Lost",
  "Enraging",
  "Evasive",
  "Every 3 seconds adds 3 Frenzy, Power or Endurance charges for 9 seconds",
  "Every 8 seconds Flee for 4 seconds While fleeing avoid 75% of Damage from Hits, gain 200% increased Movement Speed and 1000% increased Evasion Rating While fleeing cast Frost Walls targeting players (1.5 second cooldown, 1.5 second global cooldown) While not fleeing take 50% less damage over time",
  "Every 9 seconds become Frenzied for 5 seconds 40% increased Damage while Frenzied 25% increased Action Speed while Frenzied 50% reduced Damage Taken while Frenzied",
  "Executioner's",
  "Explodes Corpses",
  "Exploding Crystals when Hit",
  "Exploding Orbs",
  "Extra Chaos Damage",
  "Extra Cold Damage and Exposure",
  "Extra Crits",
  "Extra Damage to Injured Foes",
  "Extra Fire Damage and Exposure",
  "Extra Life",
  "Extra Lightning Damage and Exposure",
  "Extra Physical Damage Aura",
  "Extra Projectiles",
  "Far Shot",
  "Fast Energy Shield Recharge",
  "Fecund",
  "Fire and Ignite Resistant",
  "Fire Walker's",
  "Fires crystals under Players when they hit you (0.2 second cooldown) Crystals deal no damage and despawn after 12 seconds Crystals charge up and explode on death, dealing Chaos damage",
  "Fires Mortars",
  "Flame-Retaliation",
  "Flasks lose 6 Charges every 3 seconds and you cannot gain Flask Charges",
  "Frenzy Charge on Hit",
  "Gain 1 Endurance Charge every second if you've been Hit Recently",
  "Gain 15% of Non-Chaos Damage as extra Chaos Damage",
  "Gain 50% of Physical Damage as Extra Cold Damage Inflict Cold Exposure on Hit, applying -25% to Cold Resistance",
  "Gain 50% of Physical Damage as Extra Fire Damage Inflict Fire Exposure on Hit, applying -25% to Fire Resistance",
  "Gain 50% of Physical Damage as Extra Lightning Damage Inflict Lightning Exposure on Hit, applying -25% to Lightning Resistance",
  "Gain 60% of Physical Damage as Extra Damage of a random Element Elemental Equilibrium (25% exposure )",
  "Gain a Power Charge on casting a Spell",
  "Gains increased Damage with life lost up to 40% at zero life Gains Increased Movement Speed with life lost up to 40% at zero life Gains Increased Attack and Cast Speed with life lost up to 75% at zero life Gains reduced Damage Taken with life lost up to 30% at zero life Gains increased Character Size with life lost up to 50% at zero life",
  "Gains Random Charges",
  "Gains Souls when nearby allies die Each Soul grants 5% increased Damage, Attack Speed and Cast Speed Each Soul grants 1% increased Character Size Each Soul grants 2% less damage taken to monsters Summons a Shackled Phantasm monster every 4 seconds",
  "Grants +#% resistance and +#% maximum resistance matching the highest damage type taken (Fire, Cold, Lightning or Chaos) from a hit",
  "Haste Aura",
  "Hasted",
  "Heals Allies and Suppresses Foe Recovery",
  "Heralding",
  "Hexproof",
  "Hinder Aura",
  "Hits always Ignite",
  "Hits always Shock",
  "Ice Prison",
  "Ice-Retaliation",
  "Ignites",
  "immobile 0 magic 0 default 1000",
  "Increased Area of Effect",
  "Inferno Bolt when Hit",
  "Inflicts Corrupted Blood",
  "Inflicts Corrupted Blood on Hit Inflicts Corrupted Blood when Hit Corrupted Blood lasts for 4 seconds",
  "Inflicts Grasping Vines",
  "Innocence-touched",
  "Invulnerability Aura",
  "Kitava-touched",
  "Leaves a Trail of Burning Ground",
  "Leaves a Trail of Chilled Ground",
  "Leaves a Trail of Shocked Ground",
  "Leeches Life",
  "Life Cannot Be Leeched",
  "Life Regen",
  "Life Shared with Treant Minions",
  "Lightning and Shock Resistant",
  "Lightning Mirage when Hit",
  "Lightning Storm",
  "Lightning Totem Minions",
  "Lightning Walker's",
  "Lightning-Retaliation",
  "Lunaris-touched",
  "magic 0 caster 0 default 1000",
  "magic 0 default 1000",
  "magic 0 default 1500",
  "magic 0 default 2500",
  "magic 0 default 3000",
  "magic 0 default 800",
  "magic 0 ranged 1500",
  "Marked",
  "Minions Cold Explode on Death",
  "Minions create Flame Beacons on Death",
  "Minions create Lightning Beacons on Death",
  "Minions Fire Explode on Death",
  "Minions have 40% increased Damage Minions have 150% increased maximum Life",
  "Minions Lightning Explode on Death",
  "Mirror Images",
  "Mirrored",
  "Molten Shell",
  "Name",
  "Nearby Allies have 100% increased Accuracy Rating and 100% increased Critical Strike Chance ( Accuracy and Crits Aura )",
  "Nearby Allies have 30% increased Attack and Cast Speed ( Speed Aura ) Nearby Allies have 30% increased Movement Speed ( Speed Aura )",
  "Nearby Allies have 40% increased Global Physical Damage",
  "Nearby Allies have 40% of Maximum Life as Extra Maximum Energy Shield",
  "Nearby Enemies are Hindered with 30% reduced Movement Speed",
  "Nearby Enemies cannot Recover Life or Energy Shield to above 50% (note: Executioner aura does not affect Player minions)",
  "Non-Damaging Ailments Reflection",
  "of Arcane Energy",
  "of Blinding",
  "of Bloodletting",
  "of Bombardment",
  "of Chilling Death",
  "of Clones",
  "of Congealment",
  "of Cycling",
  "of Cycling &#91; confirmation needed &#93;",
  "of Damaging",
  "of Deadliness",
  "of Detonation",
  "of Discipline",
  "of Drought",
  "of Effigies",
  "of Electricity",
  "of Endurance",
  "of Enervation",
  "of Exile",
  "of Far Shot",
  "of Flames",
  "of Flaming Death",
  "of Fleeing",
  "of Freezing",
  "of Frenzy",
  "of Giants",
  "of Haste",
  "of Hindering",
  "of Ignition",
  "of Impact",
  "of Incision",
  "of Power",
  "of Precision",
  "of Recovery",
  "of Revival",
  "of Rime",
  "of Shocking",
  "of Shocking Death",
  "of Splintering",
  "of the Barrier",
  "of the Cold Walker",
  "of the Equilibrium",
  "of the Executioner",
  "of the Fire Walker",
  "of the Hydra",
  "of the Ice",
  "of the Lightning Walker",
  "of the Magma",
  "of the Marksman",
  "of the Taskmaster",
  "of the Tempest",
  "of the Undead",
  "of the Void",
  "of Toughness",
  "of Venom",
  "Overwhelming &#91; confirmation needed &#93;",
  "Overwhelms Physical Reduction &#91; confirmation needed &#93;",
  "Pack monsters gain 10% increased Character Size on death Pack monsters gain 40% increased Maximum Life on death",
  "Pack spawns with apparitions of each monster Monster gives 175% reduced Experience on death (Hidden) 350% reduced Quantity of Items dropped by this Monster (Hidden)",
  "Periodically casts a Healing Nova that causes nearby allies to regenerate 10% of life over 2 seconds Healing Nova applies a Verdant Spores debuff causing 60% reduced Recovery Rate of Life and Energy Shield for a duration (8 second cooldown, 5 second global cooldown) Healing Nova does not affect itself Healing Nova cannot be used if the Monster with this modifier is on full life (note: Verdant Spores do not affect Player minions)",
  "Periodically creates a barrier of Ice around the player for 5 seconds (10 second cooldown)",
  "Periodically creates several clones (8 second cooldown) Clones disappear after 5 seconds and do not drop items or grant experience Clones do not inherit mods from the original monster",
  "Periodically Enrages",
  "Periodically Fires a Nova of Fire Mortars (6 second cooldown)",
  "Periodically spawns an Exploding Orb from behind the monster that chases the player while within 70 units of a player, accelerating over time (9 second cooldown)",
  "Physical Resistant",
  "Poison on Hit",
  "Poisons",
  "Power Charge on Cast",
  "Powerful Minions",
  "Precision Aura",
  "Prevents Recovery above 50%",
  "Projectiles gain Damage as they travel farther, dealing up to 60% increased Damage with Hits to targets",
  "Quick",
  "Randomly applies Poacher's Mark , Assassin's Mark or Warlord's Mark (removed when monster dies)",
  "ranged 1500",
  "ranged 5000",
  "Rare Minions create Frost Beacons on Death",
  "Rare pack minions are replaced with Saplings 50% of Damage from Hits is taken from Rare pack minions' Life before the Rare monster",
  "Rare pack Minions spawn up to 5 Invulnerable Totems on death that cast a Lightning Nova Spell Totems can use Lightning Warp Totems despawn on death",
  "Reflector's",
  "Reflects Certain Ailments",
  "Reflects Hexes",
  "Regenerate 3% of Life per second",
  "Remora's",
  "Removes all Power, Frenzy and Endurance charges on Hit",
  "Resplendent",
  "Revives Nearby Allies on Death",
  "Revives nearby Minions &#91; confirmation needed &#93;",
  "Shakari-touched",
  "Shaper touched",
  "Shaper-touched",
  "Shocked Ground on Death",
  "Shocks",
  "Shroud Walking",
  "Siphoning",
  "Siphons Flask Charges",
  "Siphons Mana and Deals Lightning Damage",
  "Skills Chain 2 additional times Projectiles have 25% chance to be able to Chain when colliding with terrain",
  "Skills fire 4 additional Projectiles",
  "Snow Bolt when Hit",
  "Solaris-touched",
  "Soul Conduit",
  "Soul Eater",
  "Spawn Weighting",
  "Spawns apparitions of the Shaper which uses his skills",
  "Spawns Consecrated Ground for 6 seconds (6 second cooldown, 4 second global cooldown) Consecrated Ground grants 2% Life Regenerated Per Second to Allies and 50% reduced Effect of Curses",
  "Spawns hazards that deal damage and apply stacks of Astral Chains when touched, slowing movement speed; stacks are removed by moving Periodically unleashes a nova spell around the monster, dealing damage",
  "Spectral",
  "Spell Resistant",
  "Spirit Walkers",
  "Stalwart",
  "Storm Herald",
  "Stuns",
  "Summons an Effigy of a targeted player at the player's location (10 second cooldown) Effigy links to the target player Effigy is immune to damage for 2 seconds after linking to a player While linked 50% of damage from Hits taken by the Effigy is also taken by the player as reflected damage Effigy can taunt other Enemies to attack it 2 seconds after linking to the player Running away from the Effigy will sever the link between itself and the player",
  "Summons an immortal ghost of the Rare monster on death that lasts for 5 seconds Corpse cannot be destroyed Cannot be Dominated",
  "Summons an invulnerable Hexing Effigy that places 3 randomly selected Hex areas, chosen randomly from Temporal Chains , Enfeeble , Elemental Weakness , Punishment and Vulnerability Hexing Effigy can apply 5 additional Curses Hexing Effigy has 100% more Effect of Curses For a full list of Hexer's override Curse stats, see Hexer",
  "Summons Skeletons and Zombies",
  "Summons Undead",
  "Surrounded by a Magma Barrier that takes 90% of Damage from Hits up to a fixed amount When the Magma Barrier is depleted it explodes for massive Fire Damage Barrier returns 10 seconds after exploding",
  "Surrounded by a Mana Siphoning Ring Aura Enemies in the Aura take Lightning Damage Over Time and lose Mana every second Enemies standing inside the Ring are not affected by the Aura",
  "Surrounded with a Temporal Bubble which prevents all damage originating from sources outside its radius Enemies within the Temporal Bubble have 25% reduced Action Speed , 60% reduced Cooldown Recovery Rate and Debuffs on them expire 40% slower",
  "Take no Extra Damage from Critical Strikes",
  "Teleports to distant Enemies creating a Smoke Cloud (3 second cooldown)",
  "Temporal",
  "Temporal Proximity Shield",
  "Temporarily Revives",
  "Trail of Cold",
  "Trail of Fire",
  "Trail of Lightning",
  "Treant-Protected",
  "Trigger Inferno Bolt when Hit",
  "Trigger Lightning Mirage when Hit (1s cooldown to explode, 2s global cooldown)",
  "Trigger Snow Bolt when Hit",
  "Tukohama-touched",
  "Unstoppable",
  "Unwavering",
  "Up to 30 nearby monsters are raised to fight again on Death Corpse cannot be destroyed Cannot be Dominated",
  "Vined",
  "Volatile",
  "When Energy Shield is depleted, triggers a weak nova that knocks back and briefly stuns enemies (2.5 second Cooldown on players) Gain 40% of Maximum Life as Extra Maximum Energy Shield",
];

/**
 * Just the names, which is all a beast's tooltip shows: "Soul Eater",
 * "Extra Fire Damage and Exposure", "Periodically Enrages". The simulation
 * rolls from these.
 */
export const MONSTER_MOD_NAMES: string[] = [
  "Abberath-touched",
  "Accurate",
  "Adaptive Resistances",
  "Always Crits",
  "Ambushes",
  "Applies Random Mark",
  "Arakaali-touched",
  "Astral-touched",
  "Bleeds",
  "Blinds",
  "Blocks Attacks",
  "Brine King-touched",
  "Burning Ground on Death",
  "Cannot be Slowed",
  "Cannot be Stunned",
  "Caustic Orb on Death",
  "Chaining",
  "Chance to Freeze",
  "Chaos and Wither Resistant",
  "Charge Removal",
  "Chilled Ground on Death",
  "Cold, Chill and Freeze Resistant",
  "Consecrated Ground",
  "Constantly Revives Minions",
  "Creates Frost Walls and Flees",
  "Creates Voodoo Doll",
  "Crit Resistant",
  "Curses",
  "Elemental Equilibrium and Random Elemental Damage",
  "Empowers Allies",
  "Endurance Charge when Hit",
  "Energy Shield Aura",
  "Energy Shield Explodes",
  "Enrages as Life Lost",
  "Evasive",
  "Explodes Corpses",
  "Exploding Crystals when Hit",
  "Exploding Orbs",
  "Extra Chaos Damage",
  "Extra Cold Damage and Exposure",
  "Extra Crits",
  "Extra Damage to Injured Foes",
  "Extra Fire Damage and Exposure",
  "Extra Life",
  "Extra Lightning Damage and Exposure",
  "Extra Physical Damage Aura",
  "Extra Projectiles",
  "Far Shot",
  "Fast Energy Shield Recharge",
  "Fire and Ignite Resistant",
  "Fires Mortars",
  "Frenzy Charge on Hit",
  "Gains Random Charges",
  "Haste Aura",
  "Hasted",
  "Heals Allies and Suppresses Foe Recovery",
  "Hexproof",
  "Hinder Aura",
  "Ice Prison",
  "Ignites",
  "Increased Area of Effect",
  "Inferno Bolt when Hit",
  "Inflicts Corrupted Blood",
  "Inflicts Grasping Vines",
  "Innocence-touched",
  "Invulnerability Aura",
  "Kitava-touched",
  "Leeches Life",
  "Life Cannot Be Leeched",
  "Life Regen",
  "Life Shared with Treant Minions",
  "Lightning and Shock Resistant",
  "Lightning Mirage when Hit",
  "Lightning Storm",
  "Lightning Totem Minions",
  "Lunaris-touched",
  "Minions Cold Explode on Death",
  "Minions Fire Explode on Death",
  "Minions Lightning Explode on Death",
  "Mirror Images",
  "Molten Shell",
  "Name",
  "Periodically Enrages",
  "Physical Resistant",
  "Poisons",
  "Power Charge on Cast",
  "Powerful Minions",
  "Precision Aura",
  "Prevents Recovery above 50%",
  "Reflects Certain Ailments",
  "Reflects Hexes",
  "Revives Nearby Allies on Death",
  "Shakari-touched",
  "Shaper touched",
  "Shocked Ground on Death",
  "Shocks",
  "Siphons Flask Charges",
  "Siphons Mana and Deals Lightning Damage",
  "Snow Bolt when Hit",
  "Solaris-touched",
  "Soul Eater",
  "Spell Resistant",
  "Spirit Walkers",
  "Stuns",
  "Summons Undead",
  "Temporal Proximity Shield",
  "Temporarily Revives",
  "Trail of Cold",
  "Trail of Fire",
  "Trail of Lightning",
  "Tukohama-touched",
];
